name: Create release PR

run-name: Create release PR for v${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version to bump `package.json` to (format: x.y.z)"

jobs:
  create-release-pr:
    name: Create release PR

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Bump version and push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git checkout -b release/${{ inputs.version }}

          npm version ${{ inputs.version }} --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "Release extension version ${{ inputs.version }}"

          git push --set-upstream origin release/${{ inputs.version }}

      - name: Create PR
        run: |
          LAST_PR=$(gh pr list --repo ${{ github.repository }} --limit 1 --state merged --search "Release version" --json number | jq -r '.[0].number')
          RELEASE_NOTES=$(./scripts/workflows/release-notes.sh $LAST_PR ${{ env.new_version }})
          gh pr create \
            --title "Release version ${{ env.new_version }}" \
            --body $RELEASE_NOTES \
            --base main \
            --head release/${{ inputs.version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
