name: Release and publish extension

run-name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version to bump `package.json` to (format: x.y.z)"

jobs:
  create-release-pr:
    name: Create release PR

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Bump version and push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git checkout -b release/${{ inputs.version }}

          npm version ${{ inputs.version }} --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "Release extension version ${{ inputs.version }}"

          git push

      - name: Create PR
        run: |
          gh pr create \
            --title "Release version ${{ inputs.version }}" \
            --body "Release version ${{ inputs.version }}" \
            --base main \
            --head release/${{ inputs.version }}
